server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: marcasReloj-service
          uri: lb://marcasReloj-service
          predicates:
            - Path=/marcasReloj/**
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pet/**
        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/**
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/empleado/**
        - id: horasExtras-service
          uri: lb://horasExtras-service
          predicates:
            - Path=/horasExtras/**
        - id: planillaSueldo-service
          uri: lb://planillaSueldo-service
          predicates:
            - Path=/calculoPlanillas/**
        - id: reporteSueldo-service
          uri: lb://reporteSueldo-service
          predicates:
            - Path=/ReporteSueldos/**